// proto/galachain.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/galachain.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GalaChainService_GetPrice_FullMethodName            = "/galachain.GalaChainService/GetPrice"
	GalaChainService_GetBalance_FullMethodName          = "/galachain.GalaChainService/GetBalance"
	GalaChainService_ExecuteSwap_FullMethodName         = "/galachain.GalaChainService/ExecuteSwap"
	GalaChainService_WatchPrices_FullMethodName         = "/galachain.GalaChainService/WatchPrices"
	GalaChainService_CreateWalletSession_FullMethodName = "/galachain.GalaChainService/CreateWalletSession"
	GalaChainService_HealthCheck_FullMethodName         = "/galachain.GalaChainService/HealthCheck"
)

// GalaChainServiceClient is the client API for GalaChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GalaChain service for managing GalaChain operations
type GalaChainServiceClient interface {
	// Get current price for a trading pair
	GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*PriceResponse, error)
	// Get wallet balance
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	// Execute a token swap
	ExecuteSwap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapResponse, error)
	// Watch price updates (streaming)
	WatchPrices(ctx context.Context, in *WatchPricesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PriceUpdate], error)
	// Create wallet connection session
	CreateWalletSession(ctx context.Context, in *WalletSessionRequest, opts ...grpc.CallOption) (*WalletSessionResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type galaChainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGalaChainServiceClient(cc grpc.ClientConnInterface) GalaChainServiceClient {
	return &galaChainServiceClient{cc}
}

func (c *galaChainServiceClient) GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*PriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, GalaChainService_GetPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galaChainServiceClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, GalaChainService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galaChainServiceClient) ExecuteSwap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapResponse)
	err := c.cc.Invoke(ctx, GalaChainService_ExecuteSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galaChainServiceClient) WatchPrices(ctx context.Context, in *WatchPricesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PriceUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GalaChainService_ServiceDesc.Streams[0], GalaChainService_WatchPrices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPricesRequest, PriceUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GalaChainService_WatchPricesClient = grpc.ServerStreamingClient[PriceUpdate]

func (c *galaChainServiceClient) CreateWalletSession(ctx context.Context, in *WalletSessionRequest, opts ...grpc.CallOption) (*WalletSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletSessionResponse)
	err := c.cc.Invoke(ctx, GalaChainService_CreateWalletSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *galaChainServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, GalaChainService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GalaChainServiceServer is the server API for GalaChainService service.
// All implementations must embed UnimplementedGalaChainServiceServer
// for forward compatibility.
//
// GalaChain service for managing GalaChain operations
type GalaChainServiceServer interface {
	// Get current price for a trading pair
	GetPrice(context.Context, *GetPriceRequest) (*PriceResponse, error)
	// Get wallet balance
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	// Execute a token swap
	ExecuteSwap(context.Context, *SwapRequest) (*SwapResponse, error)
	// Watch price updates (streaming)
	WatchPrices(*WatchPricesRequest, grpc.ServerStreamingServer[PriceUpdate]) error
	// Create wallet connection session
	CreateWalletSession(context.Context, *WalletSessionRequest) (*WalletSessionResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedGalaChainServiceServer()
}

// UnimplementedGalaChainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGalaChainServiceServer struct{}

func (UnimplementedGalaChainServiceServer) GetPrice(context.Context, *GetPriceRequest) (*PriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedGalaChainServiceServer) GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedGalaChainServiceServer) ExecuteSwap(context.Context, *SwapRequest) (*SwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSwap not implemented")
}
func (UnimplementedGalaChainServiceServer) WatchPrices(*WatchPricesRequest, grpc.ServerStreamingServer[PriceUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchPrices not implemented")
}
func (UnimplementedGalaChainServiceServer) CreateWalletSession(context.Context, *WalletSessionRequest) (*WalletSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWalletSession not implemented")
}
func (UnimplementedGalaChainServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGalaChainServiceServer) mustEmbedUnimplementedGalaChainServiceServer() {}
func (UnimplementedGalaChainServiceServer) testEmbeddedByValue()                          {}

// UnsafeGalaChainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GalaChainServiceServer will
// result in compilation errors.
type UnsafeGalaChainServiceServer interface {
	mustEmbedUnimplementedGalaChainServiceServer()
}

func RegisterGalaChainServiceServer(s grpc.ServiceRegistrar, srv GalaChainServiceServer) {
	// If the following call panics, it indicates UnimplementedGalaChainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GalaChainService_ServiceDesc, srv)
}

func _GalaChainService_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalaChainServiceServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalaChainService_GetPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalaChainServiceServer).GetPrice(ctx, req.(*GetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalaChainService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalaChainServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalaChainService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalaChainServiceServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalaChainService_ExecuteSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalaChainServiceServer).ExecuteSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalaChainService_ExecuteSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalaChainServiceServer).ExecuteSwap(ctx, req.(*SwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalaChainService_WatchPrices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPricesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GalaChainServiceServer).WatchPrices(m, &grpc.GenericServerStream[WatchPricesRequest, PriceUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GalaChainService_WatchPricesServer = grpc.ServerStreamingServer[PriceUpdate]

func _GalaChainService_CreateWalletSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalaChainServiceServer).CreateWalletSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalaChainService_CreateWalletSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalaChainServiceServer).CreateWalletSession(ctx, req.(*WalletSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GalaChainService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GalaChainServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GalaChainService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GalaChainServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GalaChainService_ServiceDesc is the grpc.ServiceDesc for GalaChainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GalaChainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "galachain.GalaChainService",
	HandlerType: (*GalaChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrice",
			Handler:    _GalaChainService_GetPrice_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _GalaChainService_GetBalance_Handler,
		},
		{
			MethodName: "ExecuteSwap",
			Handler:    _GalaChainService_ExecuteSwap_Handler,
		},
		{
			MethodName: "CreateWalletSession",
			Handler:    _GalaChainService_CreateWalletSession_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GalaChainService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPrices",
			Handler:       _GalaChainService_WatchPrices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/galachain.proto",
}
