// proto/galachain.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/galachain.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error codes
type ErrorCode int32

const (
	ErrorCode_UNKNOWN              ErrorCode = 0
	ErrorCode_INVALID_REQUEST      ErrorCode = 1
	ErrorCode_WALLET_NOT_CONNECTED ErrorCode = 2
	ErrorCode_INSUFFICIENT_BALANCE ErrorCode = 3
	ErrorCode_SLIPPAGE_EXCEEDED    ErrorCode = 4
	ErrorCode_RATE_LIMIT_EXCEEDED  ErrorCode = 5
	ErrorCode_NETWORK_ERROR        ErrorCode = 6
	ErrorCode_TRANSACTION_FAILED   ErrorCode = 7
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INVALID_REQUEST",
		2: "WALLET_NOT_CONNECTED",
		3: "INSUFFICIENT_BALANCE",
		4: "SLIPPAGE_EXCEEDED",
		5: "RATE_LIMIT_EXCEEDED",
		6: "NETWORK_ERROR",
		7: "TRANSACTION_FAILED",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":              0,
		"INVALID_REQUEST":      1,
		"WALLET_NOT_CONNECTED": 2,
		"INSUFFICIENT_BALANCE": 3,
		"SLIPPAGE_EXCEEDED":    4,
		"RATE_LIMIT_EXCEEDED":  5,
		"NETWORK_ERROR":        6,
		"TRANSACTION_FAILED":   7,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_galachain_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_galachain_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{0}
}

// Price request for a specific trading pair
type GetPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"` // e.g., "GTON/GALA"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceRequest) Reset() {
	*x = GetPriceRequest{}
	mi := &file_proto_galachain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRequest) ProtoMessage() {}

func (x *GetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRequest.ProtoReflect.Descriptor instead.
func (*GetPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{0}
}

func (x *GetPriceRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type PriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`                          // Decimal string to avoid precision loss
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp
	Bid           string                 `protobuf:"bytes,4,opt,name=bid,proto3" json:"bid,omitempty"`                              // Bid price
	Ask           string                 `protobuf:"bytes,5,opt,name=ask,proto3" json:"ask,omitempty"`                              // Ask price
	Volume_24H    string                 `protobuf:"bytes,6,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"` // 24h volume
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceResponse) Reset() {
	*x = PriceResponse{}
	mi := &file_proto_galachain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResponse) ProtoMessage() {}

func (x *PriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResponse.ProtoReflect.Descriptor instead.
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{1}
}

func (x *PriceResponse) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *PriceResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PriceResponse) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *PriceResponse) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

func (x *PriceResponse) GetVolume_24H() string {
	if x != nil {
		return x.Volume_24H
	}
	return ""
}

// Balance request for user wallet
type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_proto_galachain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{2}
}

func (x *BalanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*TokenBalance        `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_proto_galachain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{3}
}

func (x *BalanceResponse) GetBalances() []*TokenBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type TokenBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                       // Token symbol
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`                   // Balance as decimal string
	UsdValue      string                 `protobuf:"bytes,3,opt,name=usd_value,json=usdValue,proto3" json:"usd_value,omitempty"` // USD value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenBalance) Reset() {
	*x = TokenBalance{}
	mi := &file_proto_galachain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBalance) ProtoMessage() {}

func (x *TokenBalance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBalance.ProtoReflect.Descriptor instead.
func (*TokenBalance) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{4}
}

func (x *TokenBalance) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenBalance) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *TokenBalance) GetUsdValue() string {
	if x != nil {
		return x.UsdValue
	}
	return ""
}

// Swap execution request
type SwapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromToken     string                 `protobuf:"bytes,2,opt,name=from_token,json=fromToken,proto3" json:"from_token,omitempty"`
	ToToken       string                 `protobuf:"bytes,3,opt,name=to_token,json=toToken,proto3" json:"to_token,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                               // Amount as decimal string
	SlippageBps   int32                  `protobuf:"varint,5,opt,name=slippage_bps,json=slippageBps,proto3" json:"slippage_bps,omitempty"` // Slippage in basis points (100 bps = 1%)
	FeeTier       int32                  `protobuf:"varint,6,opt,name=fee_tier,json=feeTier,proto3" json:"fee_tier,omitempty"`             // Optional fee tier override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapRequest) Reset() {
	*x = SwapRequest{}
	mi := &file_proto_galachain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapRequest) ProtoMessage() {}

func (x *SwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapRequest.ProtoReflect.Descriptor instead.
func (*SwapRequest) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{5}
}

func (x *SwapRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SwapRequest) GetFromToken() string {
	if x != nil {
		return x.FromToken
	}
	return ""
}

func (x *SwapRequest) GetToToken() string {
	if x != nil {
		return x.ToToken
	}
	return ""
}

func (x *SwapRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SwapRequest) GetSlippageBps() int32 {
	if x != nil {
		return x.SlippageBps
	}
	return 0
}

func (x *SwapRequest) GetFeeTier() int32 {
	if x != nil {
		return x.FeeTier
	}
	return 0
}

type SwapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	AmountIn      string                 `protobuf:"bytes,2,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	AmountOut     string                 `protobuf:"bytes,3,opt,name=amount_out,json=amountOut,proto3" json:"amount_out,omitempty"`
	Fee           string                 `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                 // "pending", "success", "failed"
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // If status = "failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapResponse) Reset() {
	*x = SwapResponse{}
	mi := &file_proto_galachain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapResponse) ProtoMessage() {}

func (x *SwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapResponse.ProtoReflect.Descriptor instead.
func (*SwapResponse) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{6}
}

func (x *SwapResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SwapResponse) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *SwapResponse) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *SwapResponse) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *SwapResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SwapResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Watch prices request
type WatchPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []string               `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`                              // Pairs to watch
	IntervalMs    int32                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // Update interval in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPricesRequest) Reset() {
	*x = WatchPricesRequest{}
	mi := &file_proto_galachain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPricesRequest) ProtoMessage() {}

func (x *WatchPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPricesRequest.ProtoReflect.Descriptor instead.
func (*WatchPricesRequest) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{7}
}

func (x *WatchPricesRequest) GetPairs() []string {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *WatchPricesRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type PriceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceUpdate) Reset() {
	*x = PriceUpdate{}
	mi := &file_proto_galachain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceUpdate) ProtoMessage() {}

func (x *PriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceUpdate.ProtoReflect.Descriptor instead.
func (*PriceUpdate) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{8}
}

func (x *PriceUpdate) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *PriceUpdate) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Wallet session creation
type WalletSessionRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Method string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // "walletconnect" or "manual"
	// For manual method
	PrivateKey    *string `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3,oneof" json:"private_key,omitempty"`
	PublicKey     *string `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3,oneof" json:"public_key,omitempty"`
	Address       *string `protobuf:"bytes,5,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletSessionRequest) Reset() {
	*x = WalletSessionRequest{}
	mi := &file_proto_galachain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletSessionRequest) ProtoMessage() {}

func (x *WalletSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletSessionRequest.ProtoReflect.Descriptor instead.
func (*WalletSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{9}
}

func (x *WalletSessionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WalletSessionRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WalletSessionRequest) GetPrivateKey() string {
	if x != nil && x.PrivateKey != nil {
		return *x.PrivateKey
	}
	return ""
}

func (x *WalletSessionRequest) GetPublicKey() string {
	if x != nil && x.PublicKey != nil {
		return *x.PublicKey
	}
	return ""
}

func (x *WalletSessionRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

type WalletSessionResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Method    string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// For WalletConnect
	QrCodeUri *string `protobuf:"bytes,3,opt,name=qr_code_uri,json=qrCodeUri,proto3,oneof" json:"qr_code_uri,omitempty"`
	DeepLink  *string `protobuf:"bytes,4,opt,name=deep_link,json=deepLink,proto3,oneof" json:"deep_link,omitempty"`
	// For manual
	Address       *string `protobuf:"bytes,5,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Success       bool    `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string  `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletSessionResponse) Reset() {
	*x = WalletSessionResponse{}
	mi := &file_proto_galachain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletSessionResponse) ProtoMessage() {}

func (x *WalletSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletSessionResponse.ProtoReflect.Descriptor instead.
func (*WalletSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{10}
}

func (x *WalletSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WalletSessionResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WalletSessionResponse) GetQrCodeUri() string {
	if x != nil && x.QrCodeUri != nil {
		return *x.QrCodeUri
	}
	return ""
}

func (x *WalletSessionResponse) GetDeepLink() string {
	if x != nil && x.DeepLink != nil {
		return *x.DeepLink
	}
	return ""
}

func (x *WalletSessionResponse) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *WalletSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WalletSessionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_galachain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{11}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                                       // "healthy", "degraded", "unhealthy"
	Dependencies  map[string]string      `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Dependency status
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_galachain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_galachain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_galachain_proto_rawDescGZIP(), []int{12}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetDependencies() map[string]string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_proto_galachain_proto protoreflect.FileDescriptor

const file_proto_galachain_proto_rawDesc = "" +
	"\n" +
	"\x15proto/galachain.proto\x12\tgalachain\"%\n" +
	"\x0fGetPriceRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\"\x9a\x01\n" +
	"\rPriceResponse\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03bid\x18\x04 \x01(\tR\x03bid\x12\x10\n" +
	"\x03ask\x18\x05 \x01(\tR\x03ask\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\x06 \x01(\tR\tvolume24h\")\n" +
	"\x0eBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"F\n" +
	"\x0fBalanceResponse\x123\n" +
	"\bbalances\x18\x01 \x03(\v2\x17.galachain.TokenBalanceR\bbalances\"[\n" +
	"\fTokenBalance\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12\x1b\n" +
	"\tusd_value\x18\x03 \x01(\tR\busdValue\"\xb6\x01\n" +
	"\vSwapRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"from_token\x18\x02 \x01(\tR\tfromToken\x12\x19\n" +
	"\bto_token\x18\x03 \x01(\tR\atoToken\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12!\n" +
	"\fslippage_bps\x18\x05 \x01(\x05R\vslippageBps\x12\x19\n" +
	"\bfee_tier\x18\x06 \x01(\x05R\afeeTier\"\xb2\x01\n" +
	"\fSwapResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x1b\n" +
	"\tamount_in\x18\x02 \x01(\tR\bamountIn\x12\x1d\n" +
	"\n" +
	"amount_out\x18\x03 \x01(\tR\tamountOut\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\tR\x03fee\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"K\n" +
	"\x12WatchPricesRequest\x12\x14\n" +
	"\x05pairs\x18\x01 \x03(\tR\x05pairs\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x05R\n" +
	"intervalMs\"U\n" +
	"\vPriceUpdate\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xdb\x01\n" +
	"\x14WalletSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12$\n" +
	"\vprivate_key\x18\x03 \x01(\tH\x00R\n" +
	"privateKey\x88\x01\x01\x12\"\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tH\x01R\tpublicKey\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x05 \x01(\tH\x02R\aaddress\x88\x01\x01B\x0e\n" +
	"\f_private_keyB\r\n" +
	"\v_public_keyB\n" +
	"\n" +
	"\b_address\"\x9d\x02\n" +
	"\x15WalletSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12#\n" +
	"\vqr_code_uri\x18\x03 \x01(\tH\x00R\tqrCodeUri\x88\x01\x01\x12 \n" +
	"\tdeep_link\x18\x04 \x01(\tH\x01R\bdeepLink\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x05 \x01(\tH\x02R\aaddress\x88\x01\x01\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessageB\x0e\n" +
	"\f_qr_code_uriB\f\n" +
	"\n" +
	"_deep_linkB\n" +
	"\n" +
	"\b_address\"\x14\n" +
	"\x12HealthCheckRequest\"\xeb\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12T\n" +
	"\fdependencies\x18\x02 \x03(\v20.galachain.HealthCheckResponse.DependenciesEntryR\fdependencies\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x1a?\n" +
	"\x11DependenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xbc\x01\n" +
	"\tErrorCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x01\x12\x18\n" +
	"\x14WALLET_NOT_CONNECTED\x10\x02\x12\x18\n" +
	"\x14INSUFFICIENT_BALANCE\x10\x03\x12\x15\n" +
	"\x11SLIPPAGE_EXCEEDED\x10\x04\x12\x17\n" +
	"\x13RATE_LIMIT_EXCEEDED\x10\x05\x12\x11\n" +
	"\rNETWORK_ERROR\x10\x06\x12\x16\n" +
	"\x12TRANSACTION_FAILED\x10\a2\xc9\x03\n" +
	"\x10GalaChainService\x12@\n" +
	"\bGetPrice\x12\x1a.galachain.GetPriceRequest\x1a\x18.galachain.PriceResponse\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.galachain.BalanceRequest\x1a\x1a.galachain.BalanceResponse\x12>\n" +
	"\vExecuteSwap\x12\x16.galachain.SwapRequest\x1a\x17.galachain.SwapResponse\x12F\n" +
	"\vWatchPrices\x12\x1d.galachain.WatchPricesRequest\x1a\x16.galachain.PriceUpdate0\x01\x12X\n" +
	"\x13CreateWalletSession\x12\x1f.galachain.WalletSessionRequest\x1a .galachain.WalletSessionResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.galachain.HealthCheckRequest\x1a\x1e.galachain.HealthCheckResponseB:Z8github.com/cchuter/telegram-trader/internal/galachain/pbb\x06proto3"

var (
	file_proto_galachain_proto_rawDescOnce sync.Once
	file_proto_galachain_proto_rawDescData []byte
)

func file_proto_galachain_proto_rawDescGZIP() []byte {
	file_proto_galachain_proto_rawDescOnce.Do(func() {
		file_proto_galachain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_galachain_proto_rawDesc), len(file_proto_galachain_proto_rawDesc)))
	})
	return file_proto_galachain_proto_rawDescData
}

var file_proto_galachain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_galachain_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_galachain_proto_goTypes = []any{
	(ErrorCode)(0),                // 0: galachain.ErrorCode
	(*GetPriceRequest)(nil),       // 1: galachain.GetPriceRequest
	(*PriceResponse)(nil),         // 2: galachain.PriceResponse
	(*BalanceRequest)(nil),        // 3: galachain.BalanceRequest
	(*BalanceResponse)(nil),       // 4: galachain.BalanceResponse
	(*TokenBalance)(nil),          // 5: galachain.TokenBalance
	(*SwapRequest)(nil),           // 6: galachain.SwapRequest
	(*SwapResponse)(nil),          // 7: galachain.SwapResponse
	(*WatchPricesRequest)(nil),    // 8: galachain.WatchPricesRequest
	(*PriceUpdate)(nil),           // 9: galachain.PriceUpdate
	(*WalletSessionRequest)(nil),  // 10: galachain.WalletSessionRequest
	(*WalletSessionResponse)(nil), // 11: galachain.WalletSessionResponse
	(*HealthCheckRequest)(nil),    // 12: galachain.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 13: galachain.HealthCheckResponse
	nil,                           // 14: galachain.HealthCheckResponse.DependenciesEntry
}
var file_proto_galachain_proto_depIdxs = []int32{
	5,  // 0: galachain.BalanceResponse.balances:type_name -> galachain.TokenBalance
	14, // 1: galachain.HealthCheckResponse.dependencies:type_name -> galachain.HealthCheckResponse.DependenciesEntry
	1,  // 2: galachain.GalaChainService.GetPrice:input_type -> galachain.GetPriceRequest
	3,  // 3: galachain.GalaChainService.GetBalance:input_type -> galachain.BalanceRequest
	6,  // 4: galachain.GalaChainService.ExecuteSwap:input_type -> galachain.SwapRequest
	8,  // 5: galachain.GalaChainService.WatchPrices:input_type -> galachain.WatchPricesRequest
	10, // 6: galachain.GalaChainService.CreateWalletSession:input_type -> galachain.WalletSessionRequest
	12, // 7: galachain.GalaChainService.HealthCheck:input_type -> galachain.HealthCheckRequest
	2,  // 8: galachain.GalaChainService.GetPrice:output_type -> galachain.PriceResponse
	4,  // 9: galachain.GalaChainService.GetBalance:output_type -> galachain.BalanceResponse
	7,  // 10: galachain.GalaChainService.ExecuteSwap:output_type -> galachain.SwapResponse
	9,  // 11: galachain.GalaChainService.WatchPrices:output_type -> galachain.PriceUpdate
	11, // 12: galachain.GalaChainService.CreateWalletSession:output_type -> galachain.WalletSessionResponse
	13, // 13: galachain.GalaChainService.HealthCheck:output_type -> galachain.HealthCheckResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_galachain_proto_init() }
func file_proto_galachain_proto_init() {
	if File_proto_galachain_proto != nil {
		return
	}
	file_proto_galachain_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_galachain_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_galachain_proto_rawDesc), len(file_proto_galachain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_galachain_proto_goTypes,
		DependencyIndexes: file_proto_galachain_proto_depIdxs,
		EnumInfos:         file_proto_galachain_proto_enumTypes,
		MessageInfos:      file_proto_galachain_proto_msgTypes,
	}.Build()
	File_proto_galachain_proto = out.File
	file_proto_galachain_proto_goTypes = nil
	file_proto_galachain_proto_depIdxs = nil
}
